---
title: 'OHI 2019: Compare Watson v3 and v4 '
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 1
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../workflow/templates/ohi_hdr.html'
pdf_document:
  toc: true
---

# Summary 

It seems like there were some relatively large changes in total yearly landings between version 3 and 4 of the Watson data, particularly for the non-industrial catch. To better understand (and document) the magnitude of change: Create a plot that describes total yearly catch from ~2010-2015 for last year and this year's data (Industrial and non-industrial).


# Setup

```{r setup, echo=FALSE, message=FALSE, warning=FALSE, eval=FALSE}

library(tidyverse)
library(here) # install.packages("here")
setwd(here::here("globalprep","prs_fish","v2019"))

source("https://raw.githubusercontent.com/OHI-Science/ohiprep_v2019/gh-pages/workflow/R/common.R")

rawFolder <- file.path(dir_M, "git-annex/globalprep/_raw_data/IMAS_GlobalFisheriesLandings/d2019")
rastFolder <- paste0(dir_M,"/git-annex/globalprep/prs_fish/v2019/int/")

```

```{r, eval = FALSE}
## Load this to use for comparison to last years data
index_2018 <- read.csv(file.path(dir_M, "git-annex/globalprep/_raw_data/IMAS_GlobalFisheriesLandings/d2018/Index.csv"))

## Load Files
indexInd <- read.csv(file.path(rawFolder,"IndexInd.csv")) 
indexNInd <- read.csv(file.path(rawFolder, "IndexNInd.csv"))
taxa <- read_excel(file.path(rawFolder, "Codes.xlsx"), sheet = "Taxa")
country <- read_excel(file.path(rawFolder, "Codes.xlsx"), sheet = "Country")


master <- indexInd %>%
   dplyr::full_join(indexNInd, by = c("ID","IYear", "CNumber", "Taxonkey", "Gear", "FGearCode", "NumCells"))  %>%
  dplyr::left_join(country, by = c("CNumber" = "Country")) %>%
  dplyr::left_join(taxa, by = c("Taxonkey" = "TaxonKey")) %>%
    dplyr::select(ID, Year = IYear, CountryName = `FAO name`, TaxonName, CommonName, IndReported = Reported.x, IndIUU = IUUTotal.x, IndDiscards = Discards.x, NIndReported = Reported.y, NIndIUU = IUUTotal.y, NIndDiscards = Discards.y )

master[is.na(master)] <- 0 #replace NA values with 0

DT::datatable(head(master))

## Spatial cells reference
spatialCells <- read_excel(file.path(rawFolder, "Codes.xlsx"), sheet = "Cell")
DT::datatable(head(spatialCells))
```

```{r, eval = FALSE}
master_summarise_v4 <- master %>%
  dplyr::group_by(Year) %>%
  dplyr::summarise(total_catch_Ind = sum(IndReported, IndIUU),
            total_catch_Nind = sum(NIndReported, NIndIUU),
            total_discards = sum(IndDiscards, NIndDiscards)) %>%
  dplyr::filter(Year %in% c(2010:2015)) %>%
    dplyr::mutate(version = "v4") %>%
    dplyr::mutate(total_catch_overall = total_catch_Ind + total_catch_Nind)

master_summarise_v3 <- index_2018 %>%
   dplyr::group_by(Year) %>%
  dplyr::summarise(total_catch_Ind = sum(IndReported, IndIUU),
            total_catch_Nind = sum(NIndReported, NIndIUU),
            total_discards = sum(IndDiscards, NIndDiscards)) %>%
  dplyr::filter(Year %in% c(2010:2015)) %>%
      dplyr::mutate(version = "v3",
                    total_catch_overall = total_catch_Ind + total_catch_Nind)

master_compare <- master_summarise_v3 %>%
  dplyr::full_join(master_summarise_v4) 

master_compare_gather <- master_compare %>%
  gather(key = "type", value = "catch", -Year, -version) 
  
master_compare_gather$type <- case_when(
  master_compare_gather$type == "total_catch_Nind" ~ str_sub(master_compare_gather$type,-4,-1),
  master_compare_gather$type == "total_catch_Ind" ~ str_sub(master_compare_gather$type,-3,-1),
  master_compare_gather$type == "total_catch_overall" ~ str_sub(master_compare_gather$type,-7,-1))
  
ind_plot <- master_compare_gather %>%
  ggplot(aes(x = Year, y = catch, color = type)) +
  geom_line() +
  facet_wrap(~version) +
  theme_classic() +
  labs(x = "Year", y = "Landings", title = "Global Fisheries Landings") +
  scale_color_discrete(name = "", labels = c("Commericial", "Artisanal", "Combined"))
ind_plot

ggplotly(ind_plot)

sum(master_compare_gather$catch[master_compare_gather$version == "v3" & master_compare_gather$type == "overall"]) #v3 total landings = 677930536
sum(master_compare_gather$catch[master_compare_gather$version == "v4" & master_compare_gather$type == "overall"]) #v4 total landings = 588168717
# v3 has 89761819 more landings (IUU and Reported) than v4

```


