---
title: 'OHI 2019: Natural Products'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../workflow/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---


```{r setup, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(eval=FALSE)

library(tidyverse)
source(here('workflow/R/common.R'))
```

## Load fish feed/oil catch and b/bmsy data
```{r}
forage_fish_catch <- read_csv(file.path(here(),"globalprep/fis/v2019/int/catch_fish_feed.csv")) %>%
  dplyr::select(-inWatson, -catch, -catch_human) %>%
  mutate(catch_fish_feed = ifelse(catch_fish_feed == 0, NA, catch_fish_feed))

fis_bbmsy <- read_csv(file.path(here(),"globalprep/fis/v2019/output/fis_bbmsy.csv")) %>%
  mutate(bbmsy = ifelse(bbmsy > 1 , 1, bbmsy))
```

## Align forage fish catch with b/bmsy data and calculate weighted mean
```{r}
weighted_mean_bbmsy_forage <- forage_fish_catch  %>%
  left_join(fis_bbmsy, by = c("stock_id", "rgn_id", "year")) %>%
  dplyr::filter(!is.na(bbmsy)) %>%
  group_by(year, rgn_id) %>%
  summarise(catch_weighted_mean = weighted.mean(bbmsy, catch_fish_feed)) %>%
  ungroup()

head(weighted_mean_bbmsy_forage, 10)
tail(weighted_mean_bbmsy_forage, 10)
```

## Sum forage fish catch by region and compare to NP fish oil production

```{r}

sum_forage <- forage_fish_catch %>%
  group_by(rgn_id) %>%
  summarise(total_forage_catch = sum(catch_fish_feed, na.rm = TRUE)) %>%
  ungroup()

fish_oil_tonnes <- read_csv(file.path("../output/np_harvest_tonnes.csv")) %>%
  filter(product == "fish_oil") %>%
  group_by(rgn_id) %>%
  summarise(total_fish_oil = sum(tonnes)) %>%
  ungroup()

combined <- sum_forage %>%
  left_join(fish_oil_tonnes, by = "rgn_id")

plot(combined$total_forage_catch, combined$total_fish_oil)
abline(0,1, col = "red")

combined_outliers <- sum_forage %>%
  left_join(fish_oil_tonnes, by = "rgn_id") %>%
  #dplyr::filter(rgn_id != c(138, 163, 175, 210, 223, 143)) %>%
  mutate(difference = total_forage_catch - total_fish_oil) %>%
  filter(difference < 20000)

plot(combined_outliers$total_forage_catch, combined_outliers$total_fish_oil)
abline(0,1, col = "red")

plot(combined_outliers$rgn_id, combined_outliers$difference)

```

