---
title: 'OHI 2019: Biomass Calculations '
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '../../../src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

# Summary
This analysis explores the potential use of new data to change the reference level for the mariculture subgoal.

***

# Data Source 

## GPI Phi data

**Reference**:      
Mapping the Global Potential for Marine Aquaculture (Gentry 2017)

Gentry, Rebecca R. et al. 2017. “Mapping the Global Potential for Marine Aquaculture.” Nature Ecology & Evolution 1(9): 1317–24.


Original data table is located in the supplementary information for the research paper, Supplementary Table 3, found here: https://static-content.springer.com/esm/art%3A10.1038%2Fs41559-017-0257-9/MediaObjects/41559_2017_257_MOESM1_ESM.pdf


**Description**:  

The data table contains fish and bivalve GPI averages for different countries. 

***
  
# Methods

```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)

gpi <- read.csv("karakoenig.94.1.csv") %>%
  select(-X)
```

We need to try to come up with an approach taking Phi data and converting it into tons of harvest. Ideally we can calculate in terms of yearly tons of harvest. After obtaining this we will compare the countries that we have that are easy and ignore the more complicated ones in the moment. This will allow us to see what ratio of actual harvest to potential harvest is.


